"""remove reset token

Revision ID: 249fe2446a16
Revises: 7d94e727d595
Create Date: 2025-03-15 17:54:07.782643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249fe2446a16'
down_revision = '7d94e727d595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
